#%RAML 1.0
title: Credit Service
description: Credit Service API
version: 1
mediaType: application/json
protocols:
  - HTTP
baseUri: 'http://localhost:3000/'
/creditbundles:
  get:
    responses:
      '200': {}
    queryParameters:
      user:
        example: john@gmail.com
        description: Assigned user
        type: string
        required: false
      includeExpired:
        example: true
        description: Property description
        default: true
        type: boolean
        required: false
  post:
    body:
      application/json:
        type: object
        properties:
          expiredate:
            required: true
            example: '2019-01-22'
            description: Expiration date
            type: date-only
          quantity:
            required: true
            example: 100
            description: Credit Quantity
            type: integer
          assignedto:
            required: false
            uniqueItems: true
            description: Users assigned to credit bundle
            type: array
            items:
              required: false
              example: jane@gmail.com
              type: string
  '/{id}':
    uriParameters:
      id:
        example: 82b79fa0-ff2e-11e7-9841-5f2dfd444c36
        description: Credit Bundle ID
        type: string
/credits: {}
