#%RAML 1.0
title: My super cool, example API
version: v1
baseUri: http://{environment}.api.domain.com/{version}/
mediaType: [ application/json ]

baseUriParameters:
  environment:
    type: string
    description: |
      API environment. The value can be one of "development", "stage" or "production"
      Development environment is avaibale for dev keys (client id).
      Stage is available internally only and keys are whitelisted for this environment. Keys that are not whitelisted will always return 404 for any call.
      Production is available for redular keys (klient ids).
    pattern: (development|stage|production)
    example: production

securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication for staging environment.
    type: Basic Authentication
  digest:
    description: |
      This API supports DigestSecurityScheme Authentication for staging environment.
    type: Digest Authentication
  oauth2:
    type: OAuth 2.0
    description: Test OAuth2
    describedBy:
      headers:
        Authorization:
          example: Barer 1234
    settings:
      accessTokenUri: https://domain.com/access-token
      authorizationUri: https://domain.com/auth
      authorizationGrants:  [authorization_code, client_credentials, implicit]
      scopes: [profile]
  x-test1:
    description: |
      A custom security scheme for authenticating requests.
    type: x-custom
    describedBy:
      headers:
        SpecialToken:
          description: |
            Used to send a custom token.
          type: string
      queryParameters:
        debugToken:
          description: Select one of available values to run the request in the debug mode with selected level.
          enum: [Info, Log, Warning, Error, Critical]
          type: string
          required: false
        booleanToken:
          description: Just to test boolean values.
          type: boolean
          default: true
      responses:
        401:
          description: |
            Bad token.
        403:
  x-other:
    description: |
      Other custom security method for authorization.
    type: x-custom
    describedBy:
      queryParameters:
        apiUserId:
          description: |
            Your api user ID. Some imaginary value.
          type: number
          required: true
        apiNonce:
          description: Random string
          type: string
      responses:
        401:
          description: |
            Bad token autorization.
          body:
            application/json:
              type: object
              properties:
                error:
                  type: boolean
                  description: Always true. Indicates that the response is errord.
                message:
                  type: string
                  description: Human readable message describing the error.
  oauth1:
    type: OAuth 1.0
    settings:
      authorizationUri: https://echo.advancedrestclient.com/auth/oauth1/access_token
      requestTokenUri: https://echo.advancedrestclient.com/auth/oauth1/dialog/authorize
      tokenCredentialsUri: https://echo.advancedrestclient.com/auth/oauth1/request_token
      signatures: [HMAC-SHA1, PLAINTEXT]
    describedBy:
      headers:
        Authorization:
          type: string

/endpointA:
  get:
    securedBy: [basic]
/endpointB:
  get:
    securedBy: [basic, digest]
/endpointC:
  get:
    securedBy: [null, digest]
/endpointD:
  get:
    securedBy: [null, digest, oauth1, x-other, x-test1, oauth2, basic]
/endpointE:
  get:
/endpointF:
  get:
    securedBy: [null, x-other]
